media:
  input: public/images
  output: /images

content:
  - name: posts
    label: 博客文章
    type: collection
    path: src/posts
    # 👇 关键：告诉 CMS 新建文章时生成 子目录/index.md
    filename: "{id}/index.md"
    view:
      layout: tree
      primary: name
      fields: [name, createTime]
      node:
        filename: index.md
        hideDirs: others
    fields:
      # 👇 新增：用于输入文件夹名
      - name: id
        label: ID (文件夹名)
        type: string
        required: true
      - name: name
        label: 名字
        type: string
      - name: desc
        label: 描述
        type: text
      - name: tag
        label: 标签
        type: string
        list: true
      - name: createTime
        label: 创建时间
        type: date
        options:
          format: "yyyy-MM-dd"
      - name: cover
        label: 封面
        type: image
        required: false
        options:
          extensions: [webp, jpg, png]
      - name: body
        label: 正文
        type: rich-text