media:
  input: public/images
  output: /images

content:
  - name: posts
    label: 博客文章
    type: collection
    path: src/posts
    view:
      layout: tree
      primary: name          # 👈 主键放 view 里，别放 field 里
      fields: [name, createTime]
      node:
        filename: index.md
        hideDirs: others     # 👈 加上这个，隐藏非文章目录
    fields:
      - name: name
        label: 名字
        type: string
        # 不要在这里写 primary: true，删掉

      - name: desc
        label: 描述
        type: text

      - name: tag
        label: 标签
        type: string
        list: true

      - name: createTime
        label: 创建时间
        type: date
        options:
          format: "yyyy-MM-dd"

      - name: cover
        label: 封面
        type: image
        required: false