/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links': RouteRecordInfo<
      '/links',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/[id]': RouteRecordInfo<
      '/posts/[id]',
      '/posts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/tools/': RouteRecordInfo<
      '/tools/',
      '/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/asymmetric': RouteRecordInfo<
      '/tools/asymmetric',
      '/tools/asymmetric',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/conversion/': RouteRecordInfo<
      '/tools/conversion/',
      '/tools/conversion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/conversion/document': RouteRecordInfo<
      '/tools/conversion/document',
      '/tools/conversion/document',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/conversion/image': RouteRecordInfo<
      '/tools/conversion/image',
      '/tools/conversion/image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/conversion/video': RouteRecordInfo<
      '/tools/conversion/video',
      '/tools/conversion/video',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/encryption/': RouteRecordInfo<
      '/tools/encryption/',
      '/tools/encryption',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/encryption/asymmetric': RouteRecordInfo<
      '/tools/encryption/asymmetric',
      '/tools/encryption/asymmetric',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/encryption/hash': RouteRecordInfo<
      '/tools/encryption/hash',
      '/tools/encryption/hash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/encryption/symmetric': RouteRecordInfo<
      '/tools/encryption/symmetric',
      '/tools/encryption/symmetric',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/hash': RouteRecordInfo<
      '/tools/hash',
      '/tools/hash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/network/': RouteRecordInfo<
      '/tools/network/',
      '/tools/network',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/network/cert': RouteRecordInfo<
      '/tools/network/cert',
      '/tools/network/cert',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/network/cidr': RouteRecordInfo<
      '/tools/network/cidr',
      '/tools/network/cidr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/network/ip': RouteRecordInfo<
      '/tools/network/ip',
      '/tools/network/ip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/network/ping': RouteRecordInfo<
      '/tools/network/ping',
      '/tools/network/ping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/network/speedtest': RouteRecordInfo<
      '/tools/network/speedtest',
      '/tools/network/speedtest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/symmetric': RouteRecordInfo<
      '/tools/symmetric',
      '/tools/symmetric',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/links.vue': {
      routes:
        | '/links'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/posts/[id].vue': {
      routes:
        | '/posts/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/tools/index.vue': {
      routes:
        | '/tools/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/asymmetric.vue': {
      routes:
        | '/tools/asymmetric'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/conversion/index.vue': {
      routes:
        | '/tools/conversion/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/conversion/document.vue': {
      routes:
        | '/tools/conversion/document'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/conversion/image.vue': {
      routes:
        | '/tools/conversion/image'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/conversion/video.vue': {
      routes:
        | '/tools/conversion/video'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/encryption/index.vue': {
      routes:
        | '/tools/encryption/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/encryption/asymmetric.vue': {
      routes:
        | '/tools/encryption/asymmetric'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/encryption/hash.vue': {
      routes:
        | '/tools/encryption/hash'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/encryption/symmetric.vue': {
      routes:
        | '/tools/encryption/symmetric'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/hash.vue': {
      routes:
        | '/tools/hash'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/network/index.vue': {
      routes:
        | '/tools/network/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/network/cert.vue': {
      routes:
        | '/tools/network/cert'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/network/cidr.vue': {
      routes:
        | '/tools/network/cidr'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/network/ip.vue': {
      routes:
        | '/tools/network/ip'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/network/ping.vue': {
      routes:
        | '/tools/network/ping'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/network/speedtest.vue': {
      routes:
        | '/tools/network/speedtest'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tools/symmetric.vue': {
      routes:
        | '/tools/symmetric'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
